# Generated by Django 3.1.2 on 2020-11-06 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 11, 6, 11, 37, 10, 810140))),
            ],
        ),
    ]
