# Generated by Django 3.1.2 on 2020-11-08 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentblog', '0005_auto_20201108_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 14, 53, 24, 951788)),
        ),
    ]
