# Generated by Django 3.1.2 on 2020-11-09 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentblog', '0007_auto_20201108_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 9, 40, 2, 236091)),
        ),
    ]
