# Generated by Django 3.1.2 on 2020-11-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_usersignup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
