# Generated by Django 3.1.2 on 2020-11-04 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0006_auto_20201104_0924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSignup',
        ),
    ]
